spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
mybatis:
  # config-location: classpath:mybatis-config.xml
  type-aliases-package: com.cota.dto
  mapper-locations:
  - mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true



# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      
# 운영 환경 (AWS)
---
spring:
  profiles: real
server:
  port: 3001
spring.profiles.include: real-db